---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
  "/storage":
    post:
      summary: Upload file in storage
      tags:
      - Storage
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
        required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
